version: '3'

services:
  wordpress:
    image: wordpress
    # ports:
    #   - 80:80
    environment: 
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes: 
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    restart: always
    networks:
      - nt-frontend
      - nt-backend

  mysql:
    image: mysql:8.0
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - nt-backend
    healthcheck:
      test: mysql --user=${WORDPRESS_DB_USER} --password=${WORDPRESS_DB_PASSWORD} -e "SHOW DATABASES;"
      interval: 3s
      timeout: 3s
      retries: 4

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
    restart: always
    networks:
      - nt-frontend
      - nt-backend

  https:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: '${DOMAIN} -> http://wordpress:80'
      STAGE: 'production'
    restart: always
    networks:
      - nt-frontend
    volumes:
      - ssl_certs_data:/var/lib/https-portal

volumes: 
  mysql_data:
  wordpress_data:
  ssl_certs_data:

networks:
  nt-backend:
  nt-frontend: